"""empty message

Revision ID: 4cded7fb6c06
Revises: 25310b19587c
Create Date: 2020-02-29 12:05:50.937944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cded7fb6c06'
down_revision = '25310b19587c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event') as batch_op:
        batch_op.drop_column('test_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('test_type', sa.VARCHAR(length=8), nullable=True))
    # ### end Alembic commands ###
